# DISABLE HIBERNATE UNTIL FIXED
quarkus.hibernate-orm.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.redis.devservices.enabled=false
quarkus.log.level=INFO
quarkus.redis.enabled=false